import { precacheAndRoute } from 'workbox-precaching';

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file!
// @ts-ignore
precacheAndRoute(self.__WB_MANIFEST);

// Handle SKIP_WAITING for immediate activation
self.addEventListener('message', (event) => {
    if (event.data && event.data.type === 'SKIP_WAITING') {
        self.skipWaiting();
    }
});

self.addEventListener('push', (event) => {
    const data = event.data ? event.data.json() : { title: 'ChefScan.IA', body: '¡Tienes una nueva actualización!' };

    const options = {
        body: data.body,
        icon: '/logo-192.png',
        badge: '/logo-192.png',
        data: data.url || '/',
        vibrate: [100, 50, 100],
        actions: [
            { action: 'open', title: 'Ver ahora' }
        ]
    };

    event.waitUntil(
        self.registration.showNotification(data.title, options)
    );
});

self.addEventListener('notificationclick', (event) => {
    event.notification.close();
    event.waitUntil(
        // @ts-ignore
        clients.openWindow(event.notification.data)
    );
});
